syms PITCH ROLL W_X W_Y W_Z DOT_DOT_x_1 v_0_z v_0_x v_0_y DOT_DOT_x_3 DOT_DOT_y_2 DOT_DOT_y_4 DOT_x_1 DOT_x_3 DOT_y_2 DOT_y_4 x_1 x_3 y_2 y_4 m_b z_m z_r L g m m_b M BETA I_b_XX I_b_YY I_b_ZZ b_f b_m zeta_1 zeta_2 zeta_3 zeta_4 OMEGA_1 OMEGA_2 OMEGA_3 OMEGA_4 REAL



MI = m/M;
x13 = x_1 + x_3;
y24 = y_2 +  y_4;


DOT_x13 = DOT_x_1 + DOT_x_3;
DOT_y24 = DOT_y_2 +  DOT_y_4;

DOT_DOT_x13 = DOT_DOT_x_1 + DOT_DOT_x_3;
DOT_DOT_y24 = DOT_DOT_y_2 +  DOT_DOT_y_4;


F_r_1 = b_f * OMEGA_1^2;
F_r_2 = b_f * OMEGA_2^2;
F_r_3 = b_f * OMEGA_3^2;
F_r_4 = b_f * OMEGA_4^2;


M_r_1 =zeta_1 * b_m * b_f * OMEGA_1^2;
M_r_2 =zeta_2 * b_m * b_f * OMEGA_2^2;
M_r_3 =zeta_3 * b_m * b_f * OMEGA_3^2;
M_r_4 =zeta_4 * b_m * b_f * OMEGA_4^2;





I_b_c = [ I_b_XX + m_b*( ( MI *y24 )^2 + ( sym(4)*MI*z_m )^2 ) ,  - m_b * MI^2 * x13 * y24                              , sym(-4) * m_b * MI^2 * x13 * z_m                    ;
           - m_b * MI^2 * x13 * y24                            ,  I_b_YY + m_b*( ( MI *x13 )^2 + ( sym(4)*MI*z_m )^2 )  , sym(-4) * m_b * MI^2 * y24 * z_m                    ;
          sym(-4) * m_b * MI^2 * x13 * z_m                     ,  sym(-4) * m_b * MI^2 * y24 * z_m                      , I_b_ZZ + m_b*( ( MI * x13 )^2 + ( MI * y24 )^2 )   ];

      
I_1_c = [ m *( (MI*y24)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)              , m * MI * ( sym(0.5)*L + x_1 - MI*x13) * y24                          ,  - m * ( sym(0.5)*L + x_1 - MI*x13)*( (1 - sym(4)*MI )*z_m ) ;
           m * MI * ( sym(0.5)*L + x_1 - MI*x13) * y24                 ,  m *( (sym(0.5)*L + x_1 - MI*x13)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)  ,  m* MI* y24 * (1 - sym(4)*MI ) * z_m                         ;
           - m * ( sym(0.5)*L + x_1 - MI*x13)*( (1 - sym(4)*MI )*z_m ) , m* MI* y24 * (1 - sym(4)*MI ) * z_m                                  ,  m *( (sym(0.5)*L + x_1 - MI*x13)^2 + ( MI * y24 )^2)       ];
       
I_3_c = [ m *( (MI*y24)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)              , m * MI * ( sym(-0.5)*L + x_3 - MI*x13) * y24                          ,  - m * ( sym(-0.5)*L + x_3 - MI*x13)*( (1 - sym(4)*MI )*z_m ) ;
           m * MI * ( sym(-0.5)*L + x_3 - MI*x13) * y24                 ,  m *( (sym(-0.5)*L + x_3 - MI*x13)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)  ,  m* MI* y24 * (1 - sym(4)*MI ) * z_m                         ;
           - m * ( sym(-0.5)*L + x_3 - MI*x13)*( (1 - sym(4)*MI )*z_m ) , m* MI* y24 * (1 - sym(4)*MI ) * z_m                                  ,  m *( (sym(-0.5)*L + x_3 - MI*x13)^2 + ( MI * y24 )^2)       ];
     
I_2_c = [ m *( ( sym(0.5)*L + y_2 - MI*y24 )^2 + ((sym(1) - sym(4)*MI)*z_m)^2)              , m * MI * ( sym(0.5)*L + y_2 - MI*y24) * x13                                                    ,   m * MI * x13 * ((sym(1) - sym(4)*MI)*z_m)                     ;
           m * MI * ( sym(0.5)*L + y_2 - MI*y24) * x13                                   ,  m *( (MI * x13)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)                                             ,  - m* MI* (sym(0.5)*L + y_2 - MI*y24) * (1 - sym(4)*MI ) * z_m  ;
            m * MI * x13 * ((sym(1) - sym(4)*MI)*z_m)                                    , - m* MI* (sym(0.5)*L + y_2 - MI*y24) * (1 - sym(4)*MI ) * z_m                                  ,  m *( (sym(0.5)*L + y_2 - MI*y24)^2 + ( MI * x13 )^2)          ]; 
        

I_4_c = [ m *( ( sym(-0.5)*L + y_4 - MI*y24 )^2 + ((sym(1) - sym(4)*MI)*z_m)^2)              , m * MI * ( sym(-0.5)*L + y_4 - MI*y24) * x13                                                    ,   m * MI * x13 * ((sym(1) - sym(4)*MI)*z_m)                     ;
           m * MI * ( sym(-0.5)*L + y_4 - MI*y24) * x13                                   ,  m *( (MI * x13)^2 + ((sym(1) - sym(4)*MI)*z_m)^2)                                             ,  - m* MI* (sym(-0.5)*L + y_4 - MI*y24) * (1 - sym(4)*MI ) * z_m  ;
            m * MI * x13 * ((sym(1) - sym(4)*MI)*z_m)                                    , - m* MI* (sym(-0.5)*L + y_4 - MI*y24) * (1 - sym(4)*MI ) * z_m                                  ,  m *( (sym(-0.5)*L + y_4 - MI*y24)^2 + ( MI * x13 )^2)          ]; 
        
        
I_S_C =   I_b_c +  I_1_c + I_2_c + I_3_c + I_4_c;



M_e_x = - F_r_1 * cos(BETA) * MI * y24 ...
        - M_r_1 * sin(BETA) ...
        + F_r_2 * ( cos(BETA)*( L - MI*y24) + sin(BETA)*( z_r - sym(4)*MI*z_m)  ) ...
        - F_r_3 * cos(BETA) * MI * y24 ...
        + M_r_3*sin(BETA) ...
        + F_r_4 * ( cos(BETA)*( -L - MI*y24) - sin(BETA)*( z_r - sym(4)*MI*z_m)  );
        
M_e_y =  F_r_1 * ( cos(BETA)*( -L + MI*x13) - sin(BETA)*( z_r - sym(4)*MI*z_m)  ) ...
        + F_r_2 * cos(BETA) * MI * x13 ...
        + M_r_2 * sin(BETA) ...
        + F_r_3 * ( cos(BETA)*( L + MI*x13) + sin(BETA)*( z_r - sym(4)*MI*z_m)  ) ...
        + F_r_4 * cos(BETA) * MI * x13 ...
        - M_r_4 * sin(BETA);
   
M_e_z = - F_r_1 * sin(BETA) * MI * y24 ...
        + M_r_1 * cos(BETA) ...
        + F_r_2 * sin(BETA)*MI * x13 ...
        - M_r_2 *cos(BETA) ...
        + F_r_3 * sin(BETA) * MI * y24 ...
        + M_r_3 * cos(BETA) ...
        - F_r_4 * sin(BETA) * MI * x13 ...
        - M_r_4 * cos(BETA);
    
DOT_W_X = ( 1/I_S_C(1,1) ) * ( ...
            M_e_x - ( I_S_C(3,3) - I_S_C(2,2)) *W_Y * W_Z ...
            -2* m_b *(MI^2) * y24 * DOT_y24 * W_X ...
            -m * L * (DOT_y_2 - DOT_y_4) * W_X ...
            - 2 * m * (DOT_y_2 * y_2  + DOT_y_4 * y_4 )*(1 - 2*MI + 4*MI*MI) * W_X ...
            + 4 * m * (DOT_y_2 * y_4  + DOT_y_4 * y_2 )*(1 -  2*MI)* MI * W_X ...
            + m * W_Z * DOT_x13 * z_m * (1 - 4*MI) ...
            + m * W_Y * MI *( x13 * DOT_y24 - DOT_x13 * y24) ...
            + m * DOT_DOT_y24  * z_m * (1 - 4*MI) ...
             );
        
DOT_W_Y = ( 1/I_S_C(2,2) ) * ( ...
            M_e_y - ( I_S_C(1,1) - I_S_C(3,3)) *W_X * W_Z ...
            -2* m_b *(MI^2) * x13 * DOT_x13 * W_Y ...
            -m * L * (DOT_x_1 - DOT_x_3) * W_Y ...
            - 2 * m * (DOT_x_1 * x_1  + DOT_x_3 * x_3 )*(1 - 2*MI + 4*MI*MI) * W_Y ...
            + 4 * m * (DOT_x_1 * x_3  + DOT_x_3 * x_1 )*(1 -  2*MI)* MI * W_Y ...
            + m * W_Z * DOT_y24 * z_m * (1 - 4*MI) ...
            + m * W_X * MI *( y24 * DOT_x13 - DOT_y24 * x13) ...
            - m * DOT_DOT_x13  * z_m * (1 - 4*MI) ...
             );
         
         
DOT_W_Z = ( 1/I_S_C(3,3) ) * ( ...
            M_e_z - ( I_S_C(2,2) - I_S_C(1,1)) *W_X * W_Y ...
            - 2 * m_b * MI^2 * ( x13 * DOT_x13 + y24 * DOT_y24) * W_Z ...
            - m * L *(DOT_x_1 - DOT_x_3 + DOT_y_2 - DOT_y_4) * W_Z ...
            - 2 * m * (DOT_x_1 * x_1 + DOT_x_3 * x_3 + DOT_y_2 * y_2 + DOT_y_4 * y_4)*(1 - 2*MI + 4*MI^2) * W_Z ...
            + 4 * m *( DOT_x_1 *x_3 + DOT_x_3 * x_1 + DOT_y_2 * y_4 + DOT_y_4 * y_2) * MI *( 1 - 2*MI) * W_Z ...
            - m *( W_X * DOT_x13 + W_Y * DOT_y24) * z_m *(1 - 4*MI) ...
            + m * MI *( x13 * DOT_y24 - DOT_x13 * y24) ...
            );
       
        
        
        
        
DOT_V_X = (1/M)*(F_r_3  - F_r_1)*sin(BETA) + g*sin(PITCH) ...
           -MI*DOT_DOT_x13 + MI*W_Z*DOT_y24 ...
           +MI*(W_Y^2 + W_Z^2)*(x13) + MI*y24*(DOT_W_Z - W_X * W_Y) ...
           - 4*MI*DOT_W_Y *z_m + MI * W_Z *( DOT_y24 - 4* W_X * z_m) ...
           + v_0_y * W_Z - v_0_z * W_Y ;
       
     
DOT_V_Y = (1/M)*(F_r_4  - F_r_2)*sin(BETA) - g*cos(PITCH)*sin(ROLL) ...
           -MI*DOT_DOT_y24 - MI*W_Z*DOT_x13 ...
           +MI*(W_X^2 + W_Z^2)*(y24) - MI*x13*(DOT_W_Z + W_X * W_Y) ...
           + 4*MI*DOT_W_X*z_m - MI*W_Z *( DOT_x13 + 4* W_Y * z_m) ...
           + v_0_z * W_X - v_0_x * W_Z ;
       
       
DOT_V_Z =  (1/M)*(F_r_1 + F_r_2 + F_r_3 + F_r_4)*cos(BETA) - g*cos(ROLL)*cos(PITCH) ...
            + MI*W_Y* DOT_x13 - MI*W_X*DOT_y24 ...
            + 4*MI*(W_X^2 + W_Y^2)*z_m + MI*x13*(DOT_W_Y - W_X*W_Z) - MI*(y24)*(DOT_W_X + W_Y*W_Z) ...
            + MI*(W_Y*DOT_x13 - W_X*DOT_y24) ...
            + v_0_x*W_Y - v_0_y*W_X;
        
DOT_ROLL = W_X + sin(ROLL)*tan(PITCH)*W_Y + cos(ROLL)*tan(PITCH)*W_Z;
DOT_PITCH = cos(ROLL)*W_Y - sin(ROLL)*W_Z;
DOT_YAW = (sin(ROLL)/cos(PITCH))*W_Y + (cos(ROLL)/cos(PITCH))*W_Z;

DOT_DOT_ROLL = DOT_W_X + cos(ROLL)*DOT_ROLL*tan(PITCH)*W_Y + sin(ROLL)*(1/((cos(PITCH))^2))*DOT_PITCH*W_Y + ...
                sin(ROLL)*tan(PITCH)*DOT_W_Y - sin(ROLL)*DOT_ROLL*tan(PITCH)*W_Z + cos(ROLL)*(1/((cos(PITCH))^2))*DOT_PITCH*W_Z + ...
                cos(ROLL)*tan(PITCH)*DOT_W_Z;
          
DOT_DOT_PITCH = -sin(ROLL)*DOT_ROLL*W_Y + cos(ROLL)*DOT_W_Y - cos(ROLL)*DOT_ROLL*W_Z-sin(ROLL)*DOT_W_Z;

DOT_DOT_YAW = ((cos(ROLL)*DOT_ROLL*cos(PITCH) + sin(ROLL)*sin(PITCH)*DOT_PITCH)/((cos(PITCH))^2)) *W_Y + (sin(ROLL)/cos(PITCH))*DOT_W_Y + ...
    ((-sin(ROLL)*DOT_ROLL*cos(PITCH) + cos(ROLL)*sin(PITCH)*DOT_PITCH)/((cos(PITCH))^2)) *W_Z + (cos(ROLL)/cos(PITCH))*DOT_W_Z;